# Generated by Django 4.2.7 on 2023-11-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='searchable_table',
            field=models.BooleanField(default=False),
        ),
    ]
