# Generated by Django 4.2.7 on 2023-11-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='primary', max_length=10),
        ),
    ]
